services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./theme_ded_partners:/mnt/extra-addons/theme_ded_partners
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  odoo-db:
  odoo-data:
